### ISSUE TITLE
Banane

### ISSUE THREAD

**Issue by schultyy** [Connect-TR/Test#1]
Banane

**Comment by Connect-TR** [comment]
Ananas

Thomas Ruhnke
Analyst

[Logo_email_klein_2]

Connect Energy Economics GmbH

Gabriele-Tergit-Promenade 15
10963 Berlin

E-Mail thomas.ruhnke@connect-ee.com<mailto:thomas.ruhnke@connect-ee.com>
Tel. +49 (0) 30 8093312 34
Fax +49 (0) 30 8093312 33
URL www.connect-ee.com<http://www.connect-ee.com/>

Amtsgericht Berlin-Charlottenburg
HRB 150906 B

USt-ID: DE 290376138

Von: Jan Schulte [mailto:notifications@github.com]
Gesendet: Dienstag, 10. März 2015 15:55
An: Connect-TR/Test
Betreff: [Test] Banane (#1)


Banane
